name: CI/CD Pipeline

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2
      - name: User Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Npm Install
        run: npm install --legacy-peer-deps

      - name: rsync deployments
        run: ls -la
      - uses: easingthemes/ssh-deploy@v2.1.5
        with:
            SOURCE: "./"
            TARGET: /home/ubuntu/repos/sia-frontend-explorer
            REMOTE_HOST: 107.21.180.221
            REMOTE_USER: ubuntu
            SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
